#!/bin/bash -x

BASEDIR=$(dirname $0)
source $BASEDIR/openldap-ltb.vars


# create some directories
mkdir -p "${INSTALL_DIR}/${LDAPDATADIR}"
mkdir -p "${INSTALL_DIR}/etc/logrotate.d"
mkdir -p "${INSTALL_DIR}/etc/profile.d"
mkdir -p "${INSTALL_DIR}/lib/systemd/system"


# copy 3rd party files

## systemd
install -m 644 "${THIRD_PARTY_PATH}/${SLAPD_CLI_NAME}-${SLAPD_CLI_VERSION}/${SYSTEMD_SERVICE_NAME}.service" "${INSTALL_DIR}/lib/systemd/system/"
install -m 644 "${THIRD_PARTY_PATH}/${SLAPD_CLI_NAME}-${SLAPD_CLI_VERSION}/${SYSTEMD_LLOAD_SERVICE_NAME}.service" "${INSTALL_DIR}/lib/systemd/system"

## logrotate, profile
install -m 644 "${THIRD_PARTY_PATH}/${OPENLDAP_LOGROTATE_FILE}" "${INSTALL_DIR}/etc/logrotate.d/openldap"
install -m 755 "${THIRD_PARTY_PATH}/${OPENLDAP_PROFILE_FILE}" "${INSTALL_DIR}/etc/profile.d"

## slapd-cli
install -m 755 "${THIRD_PARTY_PATH}/${SLAPD_CLI_NAME}-${SLAPD_CLI_VERSION}/slapd-cli" "${INSTALL_DIR}${SLAPD_CLI_BIN}"
install -m 644 "${THIRD_PARTY_PATH}/${SLAPD_CLI_NAME}-${SLAPD_CLI_VERSION}/slapd-cli.conf" "${INSTALL_DIR}${SLAPD_CLI_CONF}"
install -m 644 "${THIRD_PARTY_PATH}/${SLAPD_CLI_NAME}-${SLAPD_CLI_VERSION}/config-template-2.5.conf" "${INSTALL_DIR}${SLAPD_CLI_FLAT_CONFIG_TEMPLATE}"
install -m 644 "${THIRD_PARTY_PATH}/${SLAPD_CLI_NAME}-${SLAPD_CLI_VERSION}/config-template-2.5.ldif" "${INSTALL_DIR}${SLAPD_CLI_LDIF_CONFIG_TEMPLATE}"
install -m 644 "${THIRD_PARTY_PATH}/${SLAPD_CLI_NAME}-${SLAPD_CLI_VERSION}/data-template.ldif" "${INSTALL_DIR}${SLAPD_CLI_DATA_TEMPLATE}"
install -m 640 "${THIRD_PARTY_PATH}/${SLAPD_CLI_NAME}-${SLAPD_CLI_VERSION}/lload.conf" "${INSTALL_DIR}${SLAPD_CLI_LLOAD_CONF}"
mkdir -p "${INSTALL_DIR}/etc/bash_completion.d/"
install -m 644 "${THIRD_PARTY_PATH}/${SLAPD_CLI_NAME}-${SLAPD_CLI_VERSION}/slapd-cli-prompt" "${INSTALL_DIR}/etc/bash_completion.d/"

# replace variables in slapd-cli.conf
sed -i "s:^SLAPD_PATH.*:SLAPD_PATH=\"${LDAPDIR}\":" "${INSTALL_DIR}${SLAPD_CLI_CONF}"
sed -i "s:^SLAPD_USER.*:SLAPD_USER=\"${LDAPUSER}\":" "${INSTALL_DIR}${SLAPD_CLI_CONF}"
sed -i "s:^SLAPD_GROUP.*:SLAPD_GROUP=\"${LDAPGROUP}\":" "${INSTALL_DIR}${SLAPD_CLI_CONF}"
sed -i "s:^BACKUP_PATH.*:BACKUP_PATH=\"${LDAPBACKUPDIR}\":" "${INSTALL_DIR}${SLAPD_CLI_CONF}"
sed -i "s:^SLAPD_CONF_DIR.*:SLAPD_CONF_DIR=\"${LDAPCONFDIR}\":" "${INSTALL_DIR}${SLAPD_CLI_CONF}"

# PATH modification
sed -i "s:^OL_BIN.*:OL_BIN=\"${LDAPDIR}/bin\":" "${INSTALL_DIR}/etc/profile.d/${OPENLDAP_PROFILE_FILE}"
sed -i "s:^OL_SBIN.*:OL_SBIN=\"${LDAPDIR}/sbin\":" "${INSTALL_DIR}/etc/profile.d/${OPENLDAP_PROFILE_FILE}"

# Modify data directory in slapd.conf
sed -i "s:^directory.*:directory\t\"${LDAPDATADIR}\":" "${INSTALL_DIR}${LDAPDIR}/etc/openldap/slapd.conf"

############################
# Build other dependencies
############################

# Compilation

# explockout
cd ${THIRD_PARTY_PATH}/${EXPL_NAME}-${EXPL_VERSION}
make clean
make "OLDAP_SOURCES=${BUILD_DIR}" "LIBDIR=${LDAPSERVERDIR}/libexec/openldap"
cd ${BUILD_DIR}

# contrib-overlays
cd contrib/slapd-modules
## lastbind
cd lastbind
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
## sha512
cd passwd/sha2
make clean
make "prefix=${LDAPSERVERDIR}"
cd ../..
## pbkdf2
cd passwd/pbkdf2
make clean
make "prefix=${LDAPSERVERDIR}" "LDAP_LIB="
cd ../..
## autogroup
cd autogroup
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
## smbk5pwd
cd smbk5pwd
make clean
make "DEFS=-DDO_SAMBA -DDO_SHADOW" "HEIMDAL_LIB=" "LDAP_LIB=-L../../../libraries/liblber/.libs/ -L../../../libraries/libldap/.libs/ -lldap -llber" "prefix=${LDAPSERVERDIR}"
cd ..
## nssov
cd nssov
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
## noopsrch
cd noopsrch
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
# ppm
cd ppm
make clean
make LDAP_SRC=../../.. prefix=${LDAPSERVERDIR} libdir=${LDAPSERVERDIR}/lib64
# ppm hook for 2.5.7
if [ "${REAL_VERSION}" = "2.5.7" ]; then
  :
else
  make doc prefix=${LDAPSERVERDIR}
fi
make test "LDAP_SRC=../../.."
cd ..
# variant
cd variant
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
# vc
cd vc
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..


cd ../..

# mdb-utils
cd libraries/liblmdb
make clean
make
cd ../..


# Installation

# explockout
cd ${THIRD_PARTY_PATH}/${EXPL_NAME}-${EXPL_VERSION}
mkdir -p "${INSTALL_DIR}${LDAPSERVERDIR}/libexec/openldap"
mkdir -p "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man5"
make install "OLDAP_SOURCES=${BUILD_DIR}" "DSTDIR=${INSTALL_DIR}${LDAPSERVERDIR}/libexec/openldap"
install -m 644 "slapo-explockout.5" "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man5"
cd ${BUILD_DIR}

# contrib-overlays
cd contrib/slapd-modules
cd lastbind
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd passwd/sha2
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ../..
cd passwd/pbkdf2
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ../..
cd autogroup
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd smbk5pwd
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd nssov
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd noopsrch
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd ppm
mkdir -p "${INSTALL_DIR}${PPM_CONF%/*}"
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}" "libdir=${INSTALL_DIR}${LDAPSERVERDIR}/libexec/openldap"
cp ppm_test "${INSTALL_DIR}${LDAPSERVERDIR}/libexec/openldap/"
# ppm hook for 2.5.7
if [ "${REAL_VERSION}" = "2.5.7" ]; then
  cp ../../../${THIRD_PARTY_PATH}/slapm-ppm.5 "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man5/"
fi
cd ..
cd variant
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd vc
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..


cd ../..

# mdb-utils
cd libraries/liblmdb
install -m 755 "mdb_copy" "${INSTALL_DIR}${LDAPSERVERDIR}/sbin"
install -m 755 "mdb_stat" "${INSTALL_DIR}${LDAPSERVERDIR}/sbin"
install -m 644 "mdb_copy.1" "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man1"
install -m 644 "mdb_stat.1" "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man1"
cd ../..

# Install lintian profile
mkdir -p ${INSTALL_DIR}/usr/share/lintian/profiles/debian
cp debian/openldap-ltb.lintian.profile ${INSTALL_DIR}/usr/share/lintian/profiles/debian/openldap-ltb.profile

# Clean dependency_libs field in every *.la file
find ${INSTALL_DIR} -name '*.la' | xargs -I {} sed -i "/dependency_libs/ s/'.*'/''/" {}
