# autogroup lastbind noopsrch nssov pw-pbkdf2 pw-sha2 smbk5pwd ppm variant vc
usr/local/openldap/libexec/openldap/autogroup.*
usr/local/openldap/libexec/openldap/lastbind.*
usr/local/openldap/libexec/openldap/noopsrch.*
usr/local/openldap/libexec/openldap/nssov.*
usr/local/openldap/libexec/openldap/pw-pbkdf2.*
usr/local/openldap/libexec/openldap/pw-sha2.*
usr/local/openldap/libexec/openldap/smbk5pwd.*
usr/local/openldap/libexec/openldap/ppm*
usr/local/openldap/etc/openldap/ppm.example
usr/local/openldap/libexec/openldap/variant.*
usr/local/openldap/libexec/openldap/vc.*

# man pages
usr/local/openldap/share/man/man5/slapo-lastbind.5
usr/local/openldap/share/man/man5/slapo-nssov.5
usr/local/openldap/share/man/man5/slapo-smbk5pwd.5
#usr/local/openldap/share/man/man5/slapo-ppm.5
usr/local/openldap/share/man/man5/slapo-variant.5
usr/local/openldap/share/man/man1/ldapvc.1
