#!/bin/bash -x

BASEDIR=$(dirname $0)
source $BASEDIR/openldap-ltb.vars


# create some directories
mkdir -p "${INSTALL_DIR}/${LDAPDATADIR}"
mkdir -p "${INSTALL_DIR}/etc/logrotate.d"
mkdir -p "${INSTALL_DIR}/etc/profile.d"
mkdir -p "${INSTALL_DIR}/lib/systemd/system"
mkdir -p "${INSTALL_DIR}/etc/init.d"

# Manage Systemd / init script
# systemctl if managed till debian 8,
# but we require debian >= 9 for enabling systemd script
if [ "${DEBIAN_VERSION}" -gt "8" ]; then
  # SYSTEMD SCRIPT
  
  cp -f "${SLAPD_INIT_NAME}-${SLAPD_INIT_VERSION}/slapd.service" "${INSTALL_DIR}/lib/systemd/system"
  chmod 644 "${INSTALL_DIR}/lib/systemd/system/slapd.service"

else
  # INIT SCRIPT

  cp -f "${SLAPD_INIT_NAME}-${SLAPD_INIT_VERSION}/slapd.init" "${INSTALL_DIR}/etc/init.d/slapd"
  chmod 755 "${INSTALL_DIR}/etc/init.d/slapd"
  # inject lsb functions loading in debian init script
  sed -i '/^VERSION=/a . /lib/lsb/init-functions' "${INSTALL_DIR}/etc/init.d/slapd"
  
fi


# copy some more files
cp -f "../DB_CONFIG" "${INSTALL_DIR}/${LDAPDATADIR}"
cp -f "../openldap.logrotate" "${INSTALL_DIR}/etc/logrotate.d/openldap"
cp -f "../openldap.sh" "${INSTALL_DIR}/etc/profile.d"
cp -f "${SLAPD_INIT_NAME}-${SLAPD_INIT_VERSION}/slapd-cli" "${INSTALL_DIR}/usr/local/openldap/sbin/"
cp -f "${SLAPD_INIT_NAME}-${SLAPD_INIT_VERSION}/slapd-cli.conf" "${INSTALL_DIR}/usr/local/openldap/etc/openldap/"

# replace variable in default file
sed -i "s:^SLAPD_PATH.*:SLAPD_PATH=\"${LDAPDIR}\":" "${INSTALL_DIR}${LDAPSERVERDIR}/etc/openldap/slapd-cli.conf"
sed -i "s:^SLAPD_USER.*:SLAPD_USER=\"${LDAPUSER}\":" "${INSTALL_DIR}${LDAPSERVERDIR}/etc/openldap/slapd-cli.conf"
sed -i "s:^SLAPD_GROUP.*:SLAPD_GROUP=\"${LDAPGROUP}\":" "${INSTALL_DIR}${LDAPSERVERDIR}/etc/openldap/slapd-cli.conf"
sed -i "s:^BDB_PATH.*:BDB_PATH=\"${BDBDIR}\":" "${INSTALL_DIR}${LDAPSERVERDIR}/etc/openldap/slapd-cli.conf"
sed -i "s:^DB_ARCHIVE_BIN.*:DB_ARCHIVE_BIN=\"${BDBARCHIVEBIN}\":" "${INSTALL_DIR}${LDAPSERVERDIR}/etc/openldap/slapd-cli.conf"
sed -i "s:^DB_RECOVER_BIN.*:DB_RECOVER_BIN=\"${BDBRECOVERBIN}\":" "${INSTALL_DIR}${LDAPSERVERDIR}/etc/openldap/slapd-cli.conf"
sed -i "s:^BACKUP_PATH.*:BACKUP_PATH=\"${LDAPBACKUPDIR}\":" "${INSTALL_DIR}${LDAPSERVERDIR}/etc/openldap/slapd-cli.conf"

# PATH modification
sed -i "s:^OL_BIN.*:OL_BIN=\"${LDAPDIR}/bin\":" "${INSTALL_DIR}/etc/profile.d/openldap.sh"
sed -i "s:^OL_SBIN.*:OL_SBIN=\"${LDAPDIR}/sbin\":" "${INSTALL_DIR}/etc/profile.d/openldap.sh"

# BDB configuration
sed -i "s:^set_lg_dir.*:set_lg_dir\t${LDAPLOGSDIR}:" "${INSTALL_DIR}${LDAPDATADIR}/DB_CONFIG"

# Modify data directory in slapd.conf
sed -i "s:^directory.*:directory\t\"${LDAPDATADIR}\":" "${INSTALL_DIR}${LDAPDIR}/etc/openldap/slapd.conf"

############################
# Build other dependencies
############################

# Compilation

# explockout
cd ${EXPL_NAME}-${EXPL_VERSION}
make clean
make "OLDAP_SOURCES=.." "LIBDIR=${LDAPSERVERDIR}/libexec/openldap"
cd ..

# contrib-overlays
cd contrib/slapd-modules
## lastbind
cd lastbind
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
## sha512
cd passwd/sha2
make clean
make "prefix=${LDAPSERVERDIR}"
cd ../..
## pbkdf2
cd passwd/pbkdf2
make clean
make "prefix=${LDAPSERVERDIR}" "LDAP_LIB="
cd ../..
## autogroup
cd autogroup
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
## smbk5pwd
cd smbk5pwd
make clean
make "DEFS=-DDO_SAMBA -DDO_SHADOW" "HEIMDAL_LIB=" "LDAP_LIB=-L../../../libraries/liblber/.libs/ -L../../../libraries/libldap/.libs/ -lldap -llber" "prefix=${LDAPSERVERDIR}"
cd ..
## nssov
cd nssov
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
## noopsrch
cd noopsrch
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
# ppm
cd ppm
make clean
make LDAP_SRC=../../.. prefix=${LDAPSERVERDIR} libdir=${LDAPSERVERDIR}/lib64
make test "LDAP_SRC=../../.."
cd ..
# variant
cd variant
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
# vc
cd vc
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..


cd ../..

# mdb-utils
cd libraries/liblmdb
make clean
make
cd ../..


# Installation

# explockout
cd ${EXPL_NAME}-${EXPL_VERSION}
mkdir -p "${INSTALL_DIR}${LDAPSERVERDIR}/libexec/openldap"
mkdir -p "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man5"
make install "OLDAP_SOURCES=.." "DSTDIR=${INSTALL_DIR}${LDAPSERVERDIR}/libexec/openldap"
install -m 644 "slapo-explockout.5" "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man5"
cd ..

# contrib-overlays
cd contrib/slapd-modules
cd lastbind
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd passwd/sha2
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ../..
cd passwd/pbkdf2
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ../..
cd autogroup
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd smbk5pwd
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd nssov
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd noopsrch
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd ppm
mkdir -p "${INSTALL_DIR}${PPM_CONF%/*}"
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}" "libdir=${INSTALL_DIR}${LDAPSERVERDIR}/libexec/openldap"
cp ppm_test "${INSTALL_DIR}${LDAPSERVERDIR}/libexec/openldap/"
cd ..
cd variant
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd vc
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..


cd ../..

# mdb-utils
cd libraries/liblmdb
install -m 755 "mdb_copy" "${INSTALL_DIR}${LDAPSERVERDIR}/sbin"
install -m 755 "mdb_stat" "${INSTALL_DIR}${LDAPSERVERDIR}/sbin"
install -m 644 "mdb_copy.1" "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man1"
install -m 644 "mdb_stat.1" "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man1"
cd ../..

# Install lintian profile
mkdir -p ${INSTALL_DIR}/usr/share/lintian/profiles/debian
cp debian/openldap-ltb.lintian.profile ${INSTALL_DIR}/usr/share/lintian/profiles/debian/openldap-ltb.profile

# Clean dependency_libs field in every *.la file
find ${INSTALL_DIR} -name '*.la' | xargs -I {} sed -i "/dependency_libs/ s/'.*'/''/" {}
