#!/bin/bash -x

BASEDIR=$(dirname $0)
source $BASEDIR/openldap-ltb.vars


# create some directories
mkdir -p "${INSTALL_DIR}/${LDAPDATADIR}"
mkdir -p "${INSTALL_DIR}/etc/logrotate.d"
mkdir -p "${INSTALL_DIR}/etc/profile.d"
mkdir -p "${INSTALL_DIR}/etc/init.d"
mkdir -p "${INSTALL_DIR}/etc/default"

# copy some more files
cp -f "../DB_CONFIG" "${INSTALL_DIR}/${LDAPDATADIR}"
cp -f "../openldap.logrotate" "${INSTALL_DIR}/etc/logrotate.d/openldap"
cp -f "../openldap.sh" "${INSTALL_DIR}/etc/profile.d"
cp -f "${SLAPD_INIT_NAME}-${SLAPD_INIT_VERSION}/slapd" "${INSTALL_DIR}/etc/init.d"
chmod 755 "${INSTALL_DIR}/etc/init.d/slapd"
cp -f "${SLAPD_INIT_NAME}-${SLAPD_INIT_VERSION}/slapd.default" "${INSTALL_DIR}/etc/default/slapd"

# replace variable in default file
sed -i "s:^SLAPD_PATH.*:SLAPD_PATH=\"${LDAPDIR}\":" "${INSTALL_DIR}/etc/default/slapd"
sed -i "s:^SLAPD_USER.*:SLAPD_USER=\"${LDAPUSER}\":" "${INSTALL_DIR}/etc/default/slapd"
sed -i "s:^SLAPD_GROUP.*:SLAPD_GROUP=\"${LDAPGROUP}\":" "${INSTALL_DIR}/etc/default/slapd"
sed -i "s:^BDB_PATH.*:BDB_PATH=\"${BDBDIR}\":" "${INSTALL_DIR}/etc/default/slapd"
sed -i "s:^DB_ARCHIVE_BIN.*:DB_ARCHIVE_BIN=\"${BDBARCHIVEBIN}\":" "${INSTALL_DIR}/etc/default/slapd"
sed -i "s:^DB_RECOVER_BIN.*:DB_RECOVER_BIN=\"${BDBRECOVERBIN}\":" "${INSTALL_DIR}/etc/default/slapd"
sed -i "s:^BACKUP_PATH.*:BACKUP_PATH=\"${LDAPBACKUPDIR}\":" "${INSTALL_DIR}/etc/default/slapd"

# PATH modification
sed -i "s:^OL_BIN.*:OL_BIN=\"${LDAPDIR}/bin\":" "${INSTALL_DIR}/etc/profile.d/openldap.sh"
sed -i "s:^OL_SBIN.*:OL_SBIN=\"${LDAPDIR}/sbin\":" "${INSTALL_DIR}/etc/profile.d/openldap.sh"

# BDB configuration
sed -i "s:^set_lg_dir.*:set_lg_dir\t${LDAPLOGSDIR}:" "${INSTALL_DIR}${LDAPDATADIR}/DB_CONFIG"

# Modify data directory in slapd.conf
sed -i "s:^directory.*:directory\t\"${LDAPDATADIR}\":" "${INSTALL_DIR}${LDAPDIR}/etc/openldap/slapd.conf"

############################
# Build other dependencies
############################

# Compilation

# check_password
cd ${CHECK_PASSWORD_NAME}-${CHECK_PASSWORD_VERSION}
make "CONFIG=${CHECK_PASSWORD_CONF}" "LDAP_INC=-I../include -I../servers/slapd" 
cd ..
# ppm
cd ${PPM_NAME}-${PPM_VERSION}
make "CONFIG=${PPM_CONF}" "LDAP_INC=-I../include -I../servers/slapd" 
cd ..
# contrib-overlays
cd contrib/slapd-modules
## lastbind
cd lastbind
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
## smbk5pwd
cd smbk5pwd
make clean
make "DEFS=-DDO_SAMBA -DDO_SHADOW" "HEIMDAL_LIB=" "LDAP_LIB=-L../../../libraries/liblber/.libs/ -L../../../libraries/libldap_r/.libs/ -lldap_r -llber" "prefix=${LDAPSERVERDIR}"
cd ..
## autogroup
cd autogroup
make clean
make "prefix=${LDAPSERVERDIR}"
cd ..
cd ../..
# mdb-utils
cd libraries/liblmdb
make
cd ../..


# Installation

# check_password
# library is installed in final destination because install files can't handle with variables such as ${_LIB}
mkdir -p "${INSTALL_DIR_CP}${LDAPSERVERDIR}/${_LIB}"
install -m 644 "${CHECK_PASSWORD_NAME}-${CHECK_PASSWORD_VERSION}/check_password.so" "${INSTALL_DIR_CP}${LDAPSERVERDIR}/${_LIB}"
# conf file is installed in standard tmp dir
mkdir -p "${INSTALL_DIR}${CHECK_PASSWORD_CONF%/*}"
echo "minPoints ${CHECK_PASSWORD_MINPOINTS}" > "${INSTALL_DIR}${CHECK_PASSWORD_CONF}"
echo "useCracklib ${CHECK_PASSWORD_USECRACKLIB}" >> "${INSTALL_DIR}${CHECK_PASSWORD_CONF}"
echo "minUpper ${CHECK_PASSWORD_MINUPPER}" >> "${INSTALL_DIR}${CHECK_PASSWORD_CONF}"
echo "minLower ${CHECK_PASSWORD_MINLOWER}" >> "${INSTALL_DIR}${CHECK_PASSWORD_CONF}"
echo "minDigit ${CHECK_PASSWORD_MINDIGIT}" >> "${INSTALL_DIR}${CHECK_PASSWORD_CONF}"
echo "minPunct ${CHECK_PASSWORD_MINPUNCT}" >> "${INSTALL_DIR}${CHECK_PASSWORD_CONF}"

# ppm
# library is installed in final destination because install files can't handle with variables such as ${_LIB}
mkdir -p "${INSTALL_DIR_PPM}${LDAPSERVERDIR}/${_LIB}"
install -m 644 "${PPM_NAME}-${PPM_VERSION}/ppm.so" "${INSTALL_DIR_PPM}${LDAPSERVERDIR}/${_LIB}"
# conf file is installed in standard tmp dir
mkdir -p "${INSTALL_DIR}${PPM_CONF%/*}"
install -m 644 "${PPM_NAME}-${PPM_VERSION}/ppm.conf" "${INSTALL_DIR}${PPM_CONF}"

# contrib-overlays
cd contrib/slapd-modules
cd lastbind
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd smbk5pwd
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd autogroup
make install "prefix=${INSTALL_DIR}${LDAPSERVERDIR}"
cd ..
cd ../..

# mdb-utils
cd libraries/liblmdb
install -m 755 "mdb_copy" "${INSTALL_DIR}${LDAPSERVERDIR}/sbin"
install -m 755 "mdb_stat" "${INSTALL_DIR}${LDAPSERVERDIR}/sbin"
install -m 644 "mdb_copy.1" "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man1"
install -m 644 "mdb_stat.1" "${INSTALL_DIR}${LDAPSERVERDIR}/share/man/man1"
cd ../..
