Document: openldap
Title: Debian openldap Manual
Author: <insert document author here>
Abstract: This manual describes what openldap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openldap/openldap.sgml.gz

Format: postscript
Files: /usr/share/doc/openldap/openldap.ps.gz

Format: text
Files: /usr/share/doc/openldap/openldap.text.gz

Format: HTML
Index: /usr/share/doc/openldap/html/index.html
Files: /usr/share/doc/openldap/html/*.html
