#!/bin/bash

BDBDIR="/usr/local/berkeleydb"
PATCH1="patch.4.6.21.1"
PATCH2="patch.4.6.21.2"
PATCH3="patch.4.6.21.3"
PATCH4="patch.4.6.21.4"
PATHFILE="berkeleydb.sh"
BUILDROOT="$( pwd )/debian/berkeleydb-ltb"

rm -rf ${BUILDROOT}
cd build_unix
make
cd ..
