#!/bin/bash

BDBDIR="/usr/local/berkeleydb"
PATCH1="patch.4.6.21.1"
PATCH2="patch.4.6.21.2"
PATCH3="patch.4.6.21.3"
PATCH4="patch.4.6.21.4"
PATHFILE="berkeleydb.sh"
BUILDROOT="$( pwd )/debian/berkeleydb-ltb"

cd build_unix
make install DESTDIR=${BUILDROOT}
cd ..

# PATH modification
mkdir -p ${BUILDROOT}/etc/profile.d
install -m 755 ../${PATHFILE} ${BUILDROOT}/etc/profile.d/
sed -i "s:^BDB_BIN.*:BDB_BIN=${BDBDIR}/bin:" ${BUILDROOT}/etc/profile.d/berkeleydb.sh
